repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: ruff
        name: ruff check
        entry: poetry run ruff pydeus
        language: system
        types: [python]
        stages: [commit]